version: '3.8'

services:
  frontend:
    build:
      context: ./frontend  # Path to your frontend directory
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=run.py
      - FLASK_ENV=development
    depends_on:
      - backend
    networks:
      - app-network

  backend:
    build:
      context: ./backend  # Path to your backend directory
      dockerfile: Dockerfile
    ports:
      - "8000:8000"  # Adjust port based on your backend
    environment:
      - ENV=development
    networks:
      - app-network

networks:
  app-network:
    driver: bridge